fileExists() { test -e $1 }

# Use local settings if it exists
file=~/.zshrc-local
if fileExists  $file; then
  echo "source $file"
  source $file
fi

# Source aliases
file=~/.zsh-aliases
if fileExists  $file; then
  echo "source $file"
  source $file
fi

# Source aliases
file=~/.antigen.zsh
if fileExists $file; then
  echo "source $file"
  source $file

# Load the oh-my-zsh's library.
  antigen use oh-my-zsh

# Bundles from the default repo (oh-my-zsh)
  antigen bundle common-aliases
  antigen-bundle git
  antigen bundle git-extras
  antigen bundle git-flow
  antigen bundle z

  if [[ "$OSTYPE"=="darwin"* ]]; then
    echo "osx specific bundle"
    antigen-bundle osx
  fi

# none oh-my-zsh bundles
  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh

# Load the theme.
  antigen theme nanotech

# Tell antigen that you're done.
  antigen apply
fi
